-- 0. Cleanup (Safe for reruns)
drop table if exists public.turns cascade;
drop type if exists public.turn_status cascade;
drop function if exists public.fn_join_queue cascade;
drop function if exists public.fn_advance_queue cascade;

-- 1. Create Enum for Status
create type public.turn_status as enum ('waiting', 'serving', 'completed', 'skipped');

-- 2. Create Table
create table public.turns (
  id bigint generated by default as identity primary key,
  pet_name text not null,
  owner_name text, -- Optional
  status public.turn_status not null default 'waiting',
  created_at timestamptz not null default now()
);

-- 3. Enable RLS
alter table public.turns enable row level security;

-- 4. RLS Policies
-- Allow anyone to read active turns (waiting or serving)
create policy "Enable read access for all users" on public.turns
  for select using (status in ('waiting', 'serving'));

-- 5. Indexes
create index turns_status_created_at_idx on public.turns (status, created_at);

-- 6. RPC: Join Queue
create or replace function public.fn_join_queue(
  p_pet_name text,
  p_owner_name text default null
)
returns bigint
language plpgsql
security definer -- Run as owner to bypass RLS for insert
as $$
declare
  v_id bigint;
begin
  insert into public.turns (pet_name, owner_name, status)
  values (p_pet_name, p_owner_name, 'waiting')
  returning id into v_id;
  
  return v_id;
end;
$$;

-- 7. RPC: Advance Queue
create or replace function public.fn_advance_queue(
  p_secret_code text -- Simple protection for MVP
)
returns json
language plpgsql
security definer -- Run as owner to update status
as $$
declare
  v_current_id bigint;
  v_next_id bigint;
  v_next_pet text;
begin
  -- validación "KISS" de seguridad (Hardcoded secret for MVP)
  if p_secret_code != 'DEVON_VET' then
    raise exception 'Acceso denegado: Código incorrecto';
  end if;

  -- 1. Mark current serving as completed
  update public.turns
  set status = 'completed'
  where status = 'serving';

  -- 2. Find next waiting
  select id, pet_name into v_next_id, v_next_pet
  from public.turns
  where status = 'waiting'
  order by created_at asc, id asc
  limit 1;

  -- 3. If exists, mark as serving
  if v_next_id is not null then
    update public.turns
    set status = 'serving'
    where id = v_next_id;
  end if;

  -- Return info about what happened
  return json_build_object(
    'now_serving_id', v_next_id,
    'now_serving_pet', v_next_pet
  );
end;
$$;
