-- Verificar y recrear la tabla con estructura simple y funcional
DROP TABLE IF EXISTS public.turns;

-- Crear tabla turns con estructura simple
CREATE TABLE public.turns (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pet_name TEXT NOT NULL,
  owner_name TEXT,
  status TEXT NOT NULL DEFAULT 'waiting',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Habilitar RLS
ALTER TABLE public.turns ENABLE ROW LEVEL SECURITY;

-- Políticas de seguridad
CREATE POLICY "Enable read access for all users" ON public.turns
  FOR SELECT USING (true);

CREATE POLICY "Enable insert for all users" ON public.turns
  FOR INSERT WITH CHECK (true);

CREATE POLICY "Enable update for all users" ON public.turns
  FOR UPDATE USING (true);

-- Índices
CREATE INDEX turns_status_created_at_idx ON public.turns (status, created_at);

-- Recrear funciones RPC simples
DROP FUNCTION IF EXISTS public.fn_join_queue(TEXT, TEXT);

CREATE OR REPLACE FUNCTION public.fn_join_queue(
  p_pet_name TEXT,
  p_owner_name TEXT DEFAULT NULL
)
RETURNS BIGINT
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_id BIGINT;
BEGIN
  INSERT INTO public.turns (pet_name, owner_name, status)
  VALUES (p_pet_name, p_owner_name, 'waiting')
  RETURNING id INTO v_id;
  
  RETURN v_id;
END;
$$;

DROP FUNCTION IF EXISTS public.fn_advance_queue(TEXT);

CREATE OR REPLACE FUNCTION public.fn_advance_queue(
  p_secret_code TEXT
)
RETURNS JSON
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_current_id BIGINT;
  v_next_id BIGINT;
  v_next_pet TEXT;
BEGIN
  IF p_secret_code != 'DEVON_VET' THEN
    RAISE EXCEPTION 'Acceso denegado: Código incorrecto';
  END IF;

  UPDATE public.turns
  SET status = 'completed'
  WHERE status = 'serving';

  SELECT id, pet_name INTO v_next_id, v_next_pet
  FROM public.turns
  WHERE status = 'waiting'
  ORDER BY created_at ASC, id ASC
  LIMIT 1;

  IF v_next_id IS NOT NULL THEN
    UPDATE public.turns
    SET status = 'serving'
    WHERE id = v_next_id;
  END IF;

  RETURN JSON_BUILD_OBJECT(
    'now_serving_id', v_next_id,
    'now_serving_pet', v_next_pet
  );
END;
$$;