-- Corregir estructura de tabla y funciones para que coincidan
-- Migración: fix_rpc_functions.sql

-- Verificar qué tabla existe y limpiar si es necesario
DROP TABLE IF EXISTS public.turns_temp;

-- La función fn_join_queue debería funcionar con la estructura existente
-- Si tenemos una tabla incorrecta, la recreamos
DO $$
BEGIN
    -- Verificar si existe la columna pet_name en la tabla turns
    IF NOT EXISTS (
        SELECT 1 
        FROM information_schema.columns 
        WHERE table_name = 'turns' 
        AND column_name = 'pet_name'
        AND table_schema = 'public'
    ) THEN
        -- Si no existe la columna, recreamos la tabla correctamente
        CREATE TABLE public.turns_temp AS SELECT * FROM public.turns LIMIT 0;
        DROP TABLE public.turns;
        
        CREATE TABLE public.turns (
          id bigint generated by default as identity primary key,
          pet_name text not null,
          owner_name text, -- Optional
          status public.turn_status not null default 'waiting',
          created_at timestamptz not null default now()
        );
        
        -- Habilitar RLS
        ALTER TABLE public.turns ENABLE ROW LEVEL SECURITY;
        
        -- Crear políticas
        CREATE POLICY "Enable read access for all users" ON public.turns
          FOR SELECT USING (status in ('waiting', 'serving'));
          
        CREATE POLICY "Enable insert for all users" ON public.turns
          FOR INSERT WITH CHECK (true);
          
        CREATE POLICY "Enable update for all users" ON public.turns
          FOR UPDATE USING (true);
        
        -- Crear índice
        CREATE INDEX turns_status_created_at_idx ON public.turns (status, created_at);
    END IF;
END $$;

-- Asegurarse que las funciones RPC existan y sean correctas
CREATE OR REPLACE FUNCTION public.fn_join_queue(
  p_pet_name text,
  p_owner_name text default null
)
returns bigint
language plpgsql
security definer
as $$
declare
  v_id bigint;
begin
  insert into public.turns (pet_name, owner_name, status)
  values (p_pet_name, p_owner_name, 'waiting')
  returning id into v_id;
  
  return v_id;
end;
$$;

-- Verificar que el tipo turn_status existe
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'turn_status') THEN
        CREATE TYPE public.turn_status as enum ('waiting', 'serving', 'completed', 'skipped');
    END IF;
END $$;